datagrids:
    oro-integration-grid:
        acl_resource: oro_integration_view
        source:
            type: orm
            query:
                select:
                    - c.id
                    - c.name
                    - c.type
                    - c.editMode
                    - CASE WHEN c.enabled = true THEN 'enabled' ELSE 'disabled' END as enabled
                from:
                    - { table: 'Oro\Bundle\IntegrationBundle\Entity\Channel', alias: c }
        columns:
            name:
                label:          oro.integration.integration.name.label
            type:
                label:          oro.integration.integration.type.label
                type:           twig
                template:       '@OroIntegration/Integration/Datagrid/type.html.twig'
                frontend_type:  html
                context:
                    choices:  "@oro_integration.manager.types_registry->getAvailableChannelTypesChoiceList()"
                    registry: "@oro_integration.manager.types_registry"
            enabled:
                label:          oro.integration.integration.enabled.label
                frontend_type:  select
                choices:
                    oro.integration.integration.enabled.active.label: enabled
                    oro.integration.integration.enabled.inactive.label: disabled
        properties:
            id: ~
            update_link:
                type:    url
                route:   oro_integration_update
                params:  [ id ]
            schedule_link:
                type:    url
                route:   oro_integration_schedule
                params:  [ id ]
        sorters:
            columns:
                name:    { data_name: c.name }
                type:    { data_name: c.type }
                enabled: { data_name: c.enabled }
        filters:
            columns:
                name:
                    data_name: c.name
                    type: string
                type:
                    data_name: c.type
                    type: choice
                    options:
                        field_options:
                            choices: "@oro_integration.manager.types_registry->getAvailableChannelTypesChoiceList"
                enabled:
                    data_name: c.enabled
                    type:      choice
                    options:
                        field_options:
                            choices:
                                oro.integration.integration.enabled.inactive.label: 'false'
                                oro.integration.integration.enabled.active.label: 'true'
        actions:
            update:
                type:         navigate
                link:         update_link
                acl_resource: oro_integration_update
                icon:         pencil-square-o
                label:        oro.grid.action.update
                rowAction:    true
                order:        10
            schedule:
                type:         schedule-sync
                link:         schedule_link
                acl_resource: oro_integration_update
                icon:         refresh
                label:        oro.integration.datagrid.action.schedule_sync
                order:        30
        action_configuration: ['@oro_integration.datagrid.action_configuration', 'getIsSyncAvailableCondition']
        options:
            entityHint: oro.integration.channel.entity_plural_label
            entity_pagination: true
        mass_actions:
            delete:
                disabled: true

    oro-integration-status-grid:
        acl_resource: oro_integration_view
        source:
            type: orm
            query:
                select:
                    - s.code
                    - s.date
                    - s.connector
                    - s.message
                    - i.type as integrationType
                from:
                    - { table: Oro\Bundle\IntegrationBundle\Entity\Status, alias: s }
                join:
                    left:
                        - { join: s.channel, alias: i }
                where:
                    and:
                      - s.channel = :integrationId
        columns:
            code:
                label:          oro.integration.integration_status.code.label
                frontend_type:  select
                choices:
                    oro.integration.integration_status.competed.label: 1
                    oro.integration.integration_status.failed.label: 2
            connector:
                type:     callback
                label:    oro.integration.integration_status.connector.label
                callable: "@oro_integration.datagrid.status_grid_helper->connectorCodeProperty()"
            message:
                label:          oro.integration.integration_status.message.label
                type:           twig
                template:       '@OroIntegration/Integration/Datagrid/message.html.twig'
                frontend_type:  html
            date:
                label:         oro.ui.created_at
                frontend_type: datetime
        sorters:
            columns:
                code:       { data_name: s.code }
                date:       { data_name: s.date }
                connector:  { data_name: s.connector }
            default:
                date: DESC

        properties:
            id: ~
        filters:
            columns:
                code:
                    data_name: s.code
                    type:      choice
                    options:
                        field_options:
                            choices:
                                oro.integration.integration_status.competed.label: "1"
                                oro.integration.integration_status.failed.label: "2"
                connector:
                    type:      choice
                    data_name: s.connector
                    options:
                        field_options:
                            choices: []
                message:
                    type:      string
                    data_name: s.message
                date:
                    type:      datetime
                    data_name: s.date
        options:
            entityHint: oro.integration.integration.statuses.label
            toolbarOptions:
                pageSize:
                    default_per_page: 10

    oro-integration-remote-webhook-grid:
        extended_entity_name: Oro\Bundle\IntegrationBundle\Entity\WebhookProducerSettings
        acl_resource: oro_integration_webhook_producer_settings_view
        options:
            entity_pagination: true
        source:
            type: orm
            query:
                select:
                    - rw.id
                    - rw.notificationUrl
                    - rw.topic
                    - rw.enabled
                    - rw.createdAt
                    - rw.updatedAt
                from:
                    - {table: Oro\Bundle\IntegrationBundle\Entity\WebhookProducerSettings, alias: rw}
        columns:
            topic:
                label: oro.integration.webhookproducersettings.topic.label
                type: twig
                frontend_type: html
                template: '@OroIntegration/WebhookProducerSettings/Datagrid/topic.html.twig'
            notificationUrl:
                label: oro.integration.webhookproducersettings.notification_url.label
            enabled:
                label: oro.integration.webhookproducersettings.enabled.label
                frontend_type: boolean
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label: oro.ui.updated_at
                frontend_type: datetime
        sorters:
            columns:
                notificationUrl:
                    data_name: rw.notificationUrl
                topic:
                    data_name: rw.topic
                enabled:
                    data_name: rw.enabled
                createdAt:
                    data_name: rw.createdAt
                updatedAt:
                    data_name: rw.updatedAt
            default:
                createdAt: DESC
        filters:
            columns:
                notificationUrl:
                    type: string
                    data_name: rw.notificationUrl
                topic:
                    type: string
                    data_name: rw.topic
                enabled:
                    type: boolean
                    data_name: rw.enabled
                createdAt:
                    type: datetime
                    data_name: rw.createdAt
                updatedAt:
                    type: datetime
                    data_name: rw.updatedAt
        properties:
            id: ~
            view_link:
                type: url
                route: oro_integration_webhook_producer_settings_view
                params: [id]
            update_link:
                type: url
                route: oro_integration_webhook_producer_settings_update
                params: [id]
        actions:
            view:
                type: navigate
                label: oro.grid.action.view
                link: view_link
                icon: eye
                acl_resource: oro_integration_webhook_producer_settings_view
                rowAction: true
            update:
                type: navigate
                label: oro.grid.action.update
                link: update_link
                icon: edit
                acl_resource: oro_integration_webhook_producer_settings_update
