<?php

namespace Oro\Bundle\UserBundle\Security;

use Symfony\Component\Security\Core\User\UserInterface;

interface AdvancedApiUserInterface extends UserInterface
{
    /**
     * Returns autogenerated string needed for authentication via API
     *
     * @return string
     */
    public function getApiKey();
}
