<?php

namespace Oro\Bundle\UserBundle\Security;

use Doctrine\Common\Collections\Collection;

use Oro\Bundle\UserBundle\Entity\UserApi;

/**
 * {@inheritdoc}
 */
interface AdvancedApiUserInterface
{
    /**
     * Returns autogenerated api keys collection needed for authentication via API
     *
     * @return UserApi[]|Collection
     */
    public function getApiKeys();
}
