<?php

namespace Oro\Bundle\UserBundle\Security;

interface AdvancedApiUserInterface
{
    /**
     * Returns autogenerated string needed for authentication via API
     *
     * @return string
     */
    public function getApiKey();
}
