services:
    oro_api.api_doc.documentation_provider.ext_id_integration_common_docs:
        class: Oro\Bundle\ApiBundle\ApiDoc\DocumentationProvider
        arguments:
            - '@@OroApiBundle/Resources/doc/api_ext_id/common.md'
            - '@file_locator'
        tags:
            - { name: oro.api.documentation_provider, requestType: ext_id, priority: 250 }

    oro_api.api_doc.documentation_provider.ext_id_integration_common_docs.resources:
        class: Oro\Bundle\ApiBundle\ApiDoc\ExtIdEntitiesDocumentationProvider
        arguments:
            - '%oro_api.ext_id_entities%'
            - '@oro_api.value_normalizer'
        tags:
            - { name: oro.api.documentation_provider, requestType: ext_id, priority: 245 }

    oro_api.api_doc.documentation_provider.ext_id_integration_common_docs.notes:
        class: Oro\Bundle\ApiBundle\ApiDoc\DocumentationProvider
        arguments:
            - '@@OroApiBundle/Resources/doc/api_ext_id/common_notes.md'
            - '@file_locator'
        tags:
            - { name: oro.api.documentation_provider, requestType: ext_id, priority: 240 }

    oro_api.async_operation.compute_summary:
        class: Oro\Bundle\ApiBundle\Batch\Processor\AsyncOperation\ComputeOperationSummary
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, class: Oro\Bundle\ApiBundle\Entity\AsyncOperation }

    oro_api.async_operation_errors.load_errors:
        class: Oro\Bundle\ApiBundle\Batch\Processor\AsyncOperation\LoadErrors
        arguments:
            - '@oro_api.batch.error_manager'
            - '@oro_api.batch.file_manager'
            - '@oro_api.doctrine_helper'
            - '@security.authorization_checker'
        tags:
            - { name: oro.api.processor, action: get_subresource, group: load_data, association: errors, parentClass: Oro\Bundle\ApiBundle\Entity\AsyncOperation }

    oro_api.async_operation_errors.compute_error_source:
        class: Oro\Bundle\ApiBundle\Batch\Processor\AsyncOperation\ComputeErrorSource
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, class: Oro\Bundle\ApiBundle\Batch\Model\BatchError }
