<?php

namespace Oro\Bundle\EntityExtendBundle\Tests\Unit\EventListener\Fixtures\InheritedWithAutogeneratedMap;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class ChildEntity extends BaseEntity
{
}
