oro_entity:
    exclusions:
        - { entity: Oro\Bundle\NavigationBundle\Entity\MenuUpdate }

    entity_aliases:
        Oro\Bundle\NavigationBundle\Entity\Title:
            alias:        pagetitle
            plural_alias: pagetitles
        Oro\Bundle\NavigationBundle\Entity\MenuUpdate:
            alias:        defaultmenuupdate
            plural_alias: defaultmenuupdates
