<?php

namespace Oro\Bundle\LDAPBundle\Tests\Unit\Stub;

use Oro\Bundle\UserBundle\Entity\User;

/**
 * Additional code is generated by entity extend bundle
 */
class TestingUser extends User
{
    /** @var array */
    protected $ldapMappings;

    /**
     * @return string
     */
    public function getLdapMappings()
    {
        return $this->ldapMappings;
    }

    /**
     * @param string $ldapMappings
     *
     * @return TestingUser
     */
    public function setLdapMappings($ldapMappings)
    {
        $this->ldapMappings = $ldapMappings;

        return $this;
    }
}
