<?php

namespace Oro\Bundle\LDAPBundle\Tests\Unit\Stub;

use Oro\Bundle\UserBundle\Entity\User;

/**
 * Additional code is generated by entity extend bundle
 */
class TestingUser extends User
{
    /** @var string */
    protected $dn;

    /**
     * @return string
     */
    public function getDn()
    {
        return $this->dn;
    }

    /**
     * @param string $dn
     *
     * @return TestingUser
     */
    public function setDn($dn)
    {
        $this->dn = $dn;

        return $this;
    }
}
