Oro\Bundle\IntegrationBundle\Entity\Channel:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, organization]
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
                max: 255
        type:
            - NotBlank: ~
        organization:
            - NotBlank: ~

Oro\Bundle\IntegrationBundle\Entity\WebhookProducerSettings:
    properties:
        notificationUrl:
            - NotBlank: ~
            - Url: ~
        topic:
            - NotBlank: ~
            - Oro\Bundle\IntegrationBundle\Validator\Constraints\ValidWebhookTopic: ~
        format:
            - NotBlank: ~
            - Oro\Bundle\IntegrationBundle\Validator\Constraints\ValidWebhookFormat: ~
