<?php

return [
    'with_split_parts' => [
        'entity' => 'Some\\Entity',
        'metadata' => [],
        'steps' => [
            'step_b' => [
                'order' => 0,
                'is_final' => false,
                '_is_start' => false,
                'entity_acl' => [],
                'allowed_transitions' => [],
                'position' => [],
            ],
        ],
        'transitions' => [
            'start' => [
                'step_to' => 'step_b',
                'conditional_steps_to' => [],
                'is_start' => true,
                'is_hidden' => false,
                'is_unavailable_hidden' => false,
                'acl_message' => null,
                'frontend_options' => [],
                'form_type' => 'Oro\Bundle\WorkflowBundle\Form\Type\WorkflowTransitionType',
                'display_type' => 'dialog',
                'destination_page' => '',
                'form_options' => [],
                'page_template' => null,
                'dialog_template' => null,
                'init_entities' => [],
                'init_routes' => [],
                'init_datagrids' => [],
                'init_context_attribute' => 'init_context',
                'message_parameters' => [],
                'triggers' => [],
            ],
        ],
        'attributes' => [
            'first_attribute' => [
                'type' => 'object',
                'property_path' => null,
                'options' => ['class' => 'DateTime'],
                'default' => null,
            ]
        ],
        'is_system' => false,
        'start_step' => null,
        'force_autostart' => false,
        'entity_attribute' => 'entity',
        'steps_display_ordered' => false,
        'defaults' => ['active' => false],
        'priority' => 0,
        'scopes' => [],
        'datagrids' => [],
        'disable_operations' => [],
        'applications' => [0 => 'default'],
        'transition_definitions' => [],
        'entity_restrictions' => [],
        'exclusive_active_groups' => [],
        'exclusive_record_groups' => [],
    ],
    'destination_of_split_parts' => [
        'entity' => 'Some\\Entity',
        'metadata' => [],
        'steps' => [
            'step_a' => [
                'order' => 0,
                'is_final' => false,
                '_is_start' => false,
                'entity_acl' => [],
                'allowed_transitions' => [],
                'position' => [],
            ],
        ],
        'transitions' => [
            'start' => [
                'step_to' => 'step_a',
                'conditional_steps_to' => [],
                'is_start' => true,
                'is_hidden' => false,
                'is_unavailable_hidden' => false,
                'acl_message' => null,
                'frontend_options' => [],
                'form_type' => 'Oro\Bundle\WorkflowBundle\Form\Type\WorkflowTransitionType',
                'display_type' => 'dialog',
                'destination_page' => '',
                'form_options' => [],
                'page_template' => null,
                'dialog_template' => null,
                'init_entities' => [],
                'init_routes' => [],
                'init_datagrids' => [],
                'init_context_attribute' => 'init_context',
                'message_parameters' => [],
                'triggers' => [],
            ],
        ],
        'attributes' => [
            'first_attribute' => [
                'type' => 'object',
                'property_path' => null,
                'options' => ['class' => 'DateTime'],
                'default' => null,
            ]
        ],
        'is_system' => false,
        'start_step' => null,
        'force_autostart' => false,
        'entity_attribute' => 'entity',
        'steps_display_ordered' => false,
        'defaults' => ['active' => false],
        'priority' => 0,
        'scopes' => [],
        'datagrids' => [],
        'disable_operations' => [],
        'applications' => [0 => 'default'],
        'transition_definitions' => [],
        'entity_restrictions' => [],
        'exclusive_active_groups' => [],
        'exclusive_record_groups' => [],
    ],
];
