<?php

namespace Oro\Bundle\SSOBundle\Tests\Unit\Stub;

use Oro\Bundle\UserBundle\Tests\Unit\Stub\UserStub as User;

class TestingUser extends User
{
    /**
     * This method is generated by entity extend bundle
     */
    public function setGoogleId($id)
    {
    }
}
