<?php

namespace Oro\Bundle\SSOBundle\Tests\Unit\Stub;

use Oro\Bundle\UserBundle\Entity\User;

class TestingUser extends User
{
    /**
     * This method is generated by entity extend bundle
     */
    public function setGoogleId($id)
    {
        
    }
}
