Oro\Bundle\CurrencyBundle\Entity\Price:
    constraints:
        - Oro\Bundle\CurrencyBundle\Validator\Constraints\OptionalPrice:
            groups: [Optional]
    properties:
        value:
            - NotBlank:
                message: 'oro.currency.price.value.blank'
            - Type:
                groups: [Default, Optional]
                type: numeric
                message: 'oro.currency.price.value.invalid'
            - Range:
                groups: [Default, Optional]
                minMessage: 'oro.currency.price.value.min'
                min: 0
        currency:
            - NotBlank:
                message: 'oro.currency.price.currency.blank'
            - Currency:
                groups: [Default, Optional]
                message: 'oro.currency.price.currency.invalid'

Oro\Bundle\CurrencyBundle\Entity\MultiCurrency:
    properties:
        value:
            - Type:
                groups: [Default, Optional]
                type: numeric
            - Range:
                groups: [Default, Optional]
                min: 0
        currency:
            - Currency:
                groups: [Default, Optional]
