<?php

namespace Oro\Bundle\EntityExtendBundle\Tools;

interface GeneratorExtension
{
    /**
     * Check if generator extension can be applied based on configuration
     *
     * @param array $config
     *
     * @return bool
     */
    public function isApplied(array $config);

    /**
     * Provide extension with ability to generate yaml and php files on it's own logic,
     * as well as change entity configuration before standard generator will be used
     *
     * @param array $config
     * @param bool  $isGeneratedAlready true if entity was generated by other extension
     *
     * @return bool true  - if entity generated and there's no need further processing,
     *              false - further generation will be issued
     */
    public function generate(array &$config, $isGeneratedAlready);
}
